<?php /** @var MageAustralia_AiReports_Block_Adminhtml_SavedView $this */ ?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><?= $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?= $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<div class="aireports-tabs-layout">
    <div class="aireports-tabs-layout__nav"><?= $this->getChildHtml('tabs') ?></div>
    <div class="aireports-tabs-layout__content"><div id="aireports_savedview_tabs"></div></div>
</div>
